[[constraint]]
  name = "github.com/ahmedjami/skbn"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "release-1.13"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true
